### ISSUE TITLE
README instructions wrong, can't build anymore

### ISSUE THREAD

**Issue by kunitoki** [rive-app/rive-runtime#14]
The readme mentions a hypothetical `build_rive.sh` script which is not found in the rive-cpp submodule, the only script available there is `build.sh` which needs to be executed from the rive-cpp folder (so adding rive-cpp/build on the PATH has no use).

What are the instructions to build the rive renderer ?

**Comment by ScatteredRay** [comment]
@kunitoki be careful about the PATH, as it's `rive-cpp/build` not just `rive-cpp` The file is still there for me: https://github.com/rive-app/rive-cpp/blob/master/build/build_rive.sh
