### ISSUE TITLE
Lottie to Rive

### ISSUE THREAD

**Issue by IeuanWalker** [rive-app/rive-runtime#21]
Not sure if this is the right place to raise this issue or not.

I'm trying to migrate from Lottie to Rive using the desktop app to import the lottie file and then export riv file. But the Rive animation renders the lottie file incorrectly.

This is what the lottie animation looks like - 
![image](https://github.com/user-attachments/assets/44669851-59dc-4c08-bd24-911c08ae1ed0)

This is what Rive generates -
![image](https://github.com/user-attachments/assets/216495d9-cf7b-4a39-b137-4efc95da11ae)

Here is the lottie file - 
[Location.json](https://github.com/user-attachments/files/16797980/Location.json)

**Comment by bodymovin** [comment]
Hi!
the file has a mask of type subtract that Rive doesn't support unfortunately.
That's why Rive shows the inner circle instead of the outer shape.
Perhaps a work around can be remove the clip, grouping some paths and changing the fill mode of the inner path.
