### ISSUE TITLE
Self include in rive_render_path.hpp

### ISSUE THREAD

**Issue by JCash** [rive-app/rive-runtime#23]
If you build manually using your own scripts, you might end up with different include paths, and the internal reference to itself won't be found:

https://github.com/rive-app/rive-runtime/blob/main/renderer/src/rive_render_path.hpp#L11

**Comment by csmartdalton** [comment]
Thank you for bringing this to our attention @JCash !

Unfortunately, I'm not readily able to see the issue you're reporting. Could you give more details?

**Comment by JCash** [comment]
It's because you fixed it two days ago Chris!
You need more coffee! :)

https://github.com/rive-app/rive-runtime/commit/6f2f5ae7c4d20bd394eca9c78590ab5d4884b422#diff-57f6efabfc4fed24b2a166c3bc2dbbbffe60d6565745d6c1a9f64dd0f1f455f8
